# Generated by Django 5.1.7 on 2025-04-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Тур еще не начался'), ('IN_PROGRESS', 'Тур в процессе'), ('COMPLETED', 'Тур закончен')], max_length=50, verbose_name='Статус'),
        ),
    ]
