# Generated by Django 5.1.7 on 2025-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account1', '0003_alter_avatar_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
