# Generated by Django 5.1.7 on 2025-03-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account1', '0004_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
