# Generated by Django 5.1.7 on 2025-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
