# Generated by Django 5.1.7 on 2025-03-20 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='jewelry',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='jewelry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.jewelry', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Кол-во дней'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
