# Generated by Django 5.1.7 on 2025-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_alter_favorite_options_alter_jewelry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='name',
            field=models.TextField(max_length=100, verbose_name='название'),
        ),
    ]
