# Generated by Django 5.1.7 on 2025-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_alter_jewelry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='name',
            field=models.TextField(max_length=100, verbose_name='название'),
        ),
    ]
