# Generated by Django 5.1.7 on 2025-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0007_alter_jewelry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='city',
            field=models.CharField(default=0, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Название'),
        ),
    ]
